title: "Антон Водясов | Junior Python Developer"
description: "Портфолио Python-разработчика с опытом в аналитике данных и разработке ботов"
theme: jekyll-theme-cayman
url: "https://anvod.github.io"
baseurl: "/My_GitHub_Pages"
